logsBucket: "gs://cloudbuildtestalok/buld-log"
options:
 # pool:
    # Make sure you are using the correct sharedpool
   # name: "projects/vf-de-mozart-dev/locations/europe-west3/workerPools/shared-pool"
steps:

- name: 'gcr.io/cloud-builders/docker'                                                                        
  args: ['build','--network=cloudbuild', '-t','europe-west3-docker.pkg.dev/vf-de-mozart-dev/dlake-docker/$_IMAGE_NAME:${TAG_NAME}', 'cloud-build/github-trigger/']
  
images: ['europe-west3-docker.pkg.dev/vf-de-mozart-dev/dlake-docker/$_IMAGE_NAME:${TAG_NAME}']
- id: "Cloud Run deploy"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
      [
        "run",
        "jobs",
        "create",
        "dlake-build-testing",
        "--image='europe-west3-docker.pkg.dev/vf-de-mozart-dev/dlake-docker/$_IMAGE_NAME:${TAG_NAME}'",
        "--region",
        "europe-west3",
        "--service-account=27585950716-compute@developer.gserviceaccount.com",
        "--command=python",
        "--args=main.py",
        "--platform",
       ]
 
options:
  logging: CLOUD_LOGGING_ONLY

images:
- europe-west3-
